#!/bin/bash

if [[ $# < 1 ]]; then
	echo "Usage: $(basename $0) <instance id or tag Name>"
	exit 1
fi

# Get ID by ID or tag
ID="$(awsls -t $1 | awk '{ print $1 }')"
aws ec2 start-instances --instance-ids $ID
