#!/bin/bash

if [[ $# < 1 ]]; then
	echo "Usage: $(basename $0) <instance id or tag Name> [<instance id or tag Name> ...]"
	exit 1
fi
while test $# -gt 0; do
	# Get ID by ID or tag
	ID="$(awsls -t | grep $1 | awk '{ print $1 }')"
	if [[ -z "$ID" ]]; then
		ID=$1
	fi
	aws ec2 terminate-instances --instance-ids $ID
	shift
done