#!/bin/bash
# Assign provided string to Name tag of the instance with given ID.
# If no tag value is provided, show Name tag for instance with given ID.
# If no ID is provided, show Name IDs for all instances

usage=$(cat <<USAGEBLOCK
Usage:
$(basename $0) [<instance ID> [<Name tag>]]

With no options prints IDs and Name tags for all instances.
When instance ID only is provided print Name tag value for the instance with given ID.
When both instance ID and Name tag are provided assigns the new value or changes value of the Name tag of the instance.

Profiles:
Configure additional (not default) profiles with  .aws/credential and .aws/config.
	Docs: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles
Switch profile used by this command with --profile <profile_name> option.
USAGEBLOCK
)

ARGS=()
while test $# -gt 0; do
    case "$1" in
        -h | --help)
            echo "$usage"
            exit 0
            ;;
    	--profile)
			PROFILE="--profile $2"; shift;
			;;
        --)
            shift
            break;;
        -*)
            echo "Invalid option: $1"
            echo "$usage"
            exit 1;;
        *)
			ARGS+=("$1")
    esac
    shift
done

if [[ ${#ARGS[@]} -lt 1 ]]; then
	# No arguments provided
	aws ec2 $PROFILE describe-tags --output text | grep "Name" | awk '{ print $3" "$5 }'
	exit 0
elif [[ ${#ARGS[@]} -lt 2 ]]; then
	# Only ID provided
	aws ec2 $PROFILE describe-tags --filter "Name=resource-id,Values=${ARGS[0]}"  --output text | grep "Name" | awk '{ print $5 }'
	exit 0
else
	# ID and tag value are provided
	aws ec2 $PROFILE create-tags --resources ${ARGS[0]} --tags Value=${ARGS[1]},Key=Name
fi
