#!/bin/bash

if [[ $# < 1 ]]; then
	echo "Usage: $(basename $0) <instance id or tag Name> [<instance id or tag Name> ...]"
	exit 1
fi
while test $# -gt 0; do
	# Get ID by ID or tag
	IDs=( $(awsls -t $1 | awk '{ print $1 }') )
	#echo "${#IDs[@]} ${IDs[@]}"
	if [[ -z "$IDs" ]]; then
		IDs=$1
	fi
	for ID in "${IDs[@]}"; do
		#echo "ID=$ID"
		aws ec2 terminate-instances --instance-ids $ID
	done
	shift
done